start:
	yarn start

build:
	./node_modules/.bin/webpack -d --devtool eval-cheap-module-source-map --progress --colors

build-prod:
	./node_modules/.bin/webpack -p --progress --colors

watch:
	./node_modules/.bin/webpack -d --progress --colors --watch

setup:
	yarn install
